version: '3.3'

services:
  llmbot:
    image: sudoskys/llmbot:latest
    container_name: llmbot
    volumes:
      # 挂载配置文件 settings.toml
      - ./settings.toml:/app/settings.toml
    deploy:
      resources:
        limits:
          # 保证至多有 0.90 个 CPU 和 4000MB 内存
          cpus: '0.90'
          memory: 4000M
        reservations:
          memory: 1000M
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    environment:
      AMQP_DSN: amqp://admin:8a8a8a@rabbitmq:5672
      REDIS_DSN: redis://redis:6379/0
      MONGODB_DSN: mongodb://admin:8a8a8a@mongodb:27017/?authSource=admin
    env_file:
      - .env
    networks:
      - app-tier

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbitmq
    restart: on-failure
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 8a8a8a
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - app-tier
  redis:
    container_name: redis-server
    image: redis:latest
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    networks:
      - app-tier

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=8a8a8a
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
