[bot]
master = [100]
botToken = 'key'
OPENAI_API_KEY = ["key"]
INTRO = "POWER BY OPENAI"
ABOUT = "Created by github.com/sudoskys/Openaibot"
WHITE = "Group NOT in WHITE list"

[proxy]
status = false
url = "http://127.0.0.1:7890"