[bot]
master = [100]
botToken = 'key'
# OPENAI_API_KEY = ["key"] # 使用 /add_api_key 命令来代替设置
INTRO = "POWER BY OPENAI"
ABOUT = "Created by github.com/sudoskys/Openaibot"
WHITE = "Group NOT in WHITE list"
# 加强区
Enhance_Server = { "http:/exp?q={}" = "auto", "https://search.com?q={}" = "auto" }

[proxy]
status = false
url = "http://127.0.0.1:7890"