# 不想启动就注释掉那一部分

# QQ
[Controller.QQ]
master = [222111, 11424] # master user id , 账号 ID
account = 0
verify_key = ""
INTRO = "POWER BY OPENAI"  # 后缀
ABOUT = "Created by github.com/sudoskys/Openaibot" # 关于命令返回
WHITE = "Group NOT in WHITE list" # 黑白名单提示

# Telegram
[Controller.Telegram]
master = [114, 514] # master user id , 账号 ID
botToken = '' # 机器人密钥
INTRO = "POWER BY OPENAI"  # 后缀
ABOUT = "Created by github.com/sudoskys/Openaibot" # 关于命令返回
WHITE = "Group NOT in WHITE list" # 黑白名单提示
# 设置的代理，但是不代理 openai api, 只代理 bot
proxy = { status = false, url = "http://127.0.0.1:7890" }

[Controller.BaseServer]
