# 此文件指导插件的模型使用策略，禁止出现任何 secret

[default]
group = "openai"
schema = "openai"
model = "gpt-3.5-turbo"

# 定义模型策略，为插件提供模型选择策略
[[llm]]
group = "openai"
schema = "openai"
model = "gpt-3.5-turbo"
max_tokens = 4096
available = true

[[llm]]
group = "openai"
schema = "openai"
model = "gpt-3.5-turbo-16k"
max_tokens = 16384
available = true

[[llm]]
group = "openai"
schema = "openai"
model = "gpt-3.5-turbo-0613"
max_tokens = 4096
available = true

[[llm]]
group = "openai"
schema = "openai"
model = "gpt-3.5-turbo-16k-0613"
max_tokens = 16384
available = true

[[llm]]
group = "openai"
schema = "openai"
model = "gpt-4-0613"
max_tokens = 4096
available = true

[[llm]]
group = "openai"
schema = "openai"
model = "gpt-4"
max_tokens = 16384
available = true

[[llm]]
group = "openai"
schema = "openai"
model = "gpt-4-32k"
max_tokens = 32768
available = true

[[llm]]
group = "openai"
schema = "openai"
model = "gpt-4-32k-0613"
max_tokens = 32768
available = false

